version: '3.9'

services:
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: development
    ports:
      - 3000:3000
    volumes:
      - ./backend/src:/app/src
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
