version: '3.9'

services:
  db:
    container_name: postgres
    image: postgres
    ports:
      - ${POSTGRES_PORT}:5432
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PG_DATA: /data/postgres
    volumes:
      - postgres-data-dev:/data/postgres

  dbadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    depends_on:
      - db
    restart: unless-stopped
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    volumes:
      - pgadmin-data-dev:/var/lib/pgadmin

volumes:
  postgres-data-dev:
  pgadmin-data-dev:
