version: '3.9'

services:
  db:
    container_name: postgres
    image: postgres
    ports:
      - ${POSTGRES_PORT}:5432
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PG_DATA: /data/postgres
    volumes:
      - postgres-data-dev:/data/postgres

volumes:
  postgres-data-dev:
